# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f855df92591ab6f6e79caa02da6f3989d7424866f5372bdfecad41e43bbda34220a05e3818d397cb9cc299d41cfbb2b159f30bfaef035756cf5c23891a26f851

test:
  secret_key_base: dae4eaa7bf6b2f571f6d79eebd60351ecb466a63b7eb2a70a92f7718cd0dc36c63d5fc7d36f7cadc50741dc339472ad6a044ff69a911d0424fc59aad59bb6546

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
